#!/usr/bin/env ruby
require 'rubygems'
require 'args_parser'
require 'octokit'
require 'pit'
require 'time'

args = ArgsParser.parse ARGV do
  arg :all, 'show all repos'
  arg :day, 'filter by last modified at', :default => 90
  arg :help, 'show help', :alias => :h
end

if args.has_option? :help
  STDERR.puts "show issues on GitHub.com"
  STDERR.puts args.help
  STDERR.puts
  STDERR.puts "e.g."
  STDERR.puts "  github-issues"
  STDERR.puts "  github-issues shokai"
  STDERR.puts "  github-issues shokai --all"
  exit
end

conf = Pit.get 'github.com', :require => {
  'login' => 'username on github.com',
  'password' => 'your-password'
}

client = Octokit::Client.new :login => conf['login'], :password => conf['password']

user = client.user args.argv.shift
pages = (user.public_repos + user.total_private_repos.to_i)/100 + 1

repos = 1.upto(pages).map{|page|
  puts "reading page #{page}.."
  client.repos(user.login, :per_page => 100, :page => page)
}.flatten.reject{|repo|
  repo.open_issues_count < 1
}.sort{|a,b|
  b.updated_at <=> a.updated_at
}

unless args.has_option? :all
  repos.delete_if do |repo|
    Time.parse(repo.updated_at) < Time.now - 60*60*24*60
  end
end

repos.each_with_index do |repo, i|
  puts "[#{i+1}/#{repos.size}] #{repo.html_url} (#{repo.open_issues_count} issues) [#{repo.updated_at}]"
  client.issues(repo.full_name).each do |i|
    puts " - ##{i.number}\t#{i.title}"
  end
end


